### ISSUE TITLE
Packages not loaded at the begining

### ISSUE THREAD

**Issue by acarongithub** [jomuller/ITCARES#27]
And bug due to old versions of packages (ggplot2)

**Comment by jomuller** [comment]
What's the good version of ggplot2 to use ? Last one ? It's possible can force usage of a specific version of a package if necessary.

**Comment by jomuller** [comment]
For the package DT I have 
```
Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable
```

Then, DT must be loaded after shiny.

**Comment by acarongithub** [comment]
Yes the DT package was loaded after data.table.
Sorry for the two bugs in one : ggplot2 last version is perfect.
