### ISSUE TITLE
Add a package's main page

### ISSUE THREAD

**Issue by jomuller** [jomuller/ITCARES#36]
Simply by creating an R file `ITCARES.R` with only roxygen doc. See how I did in the [vartors](https://github.com/jomuller/vartors/blob/dev/R/vartors.R) package.

**Comment by acarongithub** [comment]
Let's do that. I checked your vartors packaged and it seems pretty obvious to me. Let you check the doc once written.

**Comment by jomuller** [comment]
New plan:

- [ ] @acarongithub you will send me the text
- [ ] I will do directly the formating
