### ISSUE TITLE
Corrupted data due to new version of dplyr (0.4.3 -> 0.5.0)

### ISSUE THREAD

**Issue by jomuller** [jomuller/ITCARES#39]
```
Joining, by = "id_stay"
Joining, by = "id_stay"
Error: corrupt 'grouped_df', contains 218279 rows, and 350000 rows in groups
```

Conflict between `dplyr` and  `data.table`?

**Comment by jomuller** [comment]
Using older version of ITCARES (v0.2.4) lead to the same bug. There is probably a problem with a dependency (dplyr?)

**Comment by gficheur** [comment]
Using older version of ITCARES (v0.2.4) and previous version of dplyr (v0.4.2) : no error
Using exactly the same environment (i.e. with v0.2.4 of ITCARES) after update of dplyr (v0.5.0) : error previously described using age_study_period_restrictions

Previous result obtained for line "str(obj1)" (i.e. with dplyr v 0.4.2):

```

> str(obj1)

Classes ‘grouped_dt’, ‘tbl_dt’, ‘tbl’, ‘grouped_dt’, ‘tbl_dt’, ‘tbl’, ‘grouped_dt’, ‘tbl_dt’, ‘tbl’, ‘tbl_dt’, ‘tbl’, ‘data.table’ and 'data.frame':    338930 obs. of  3 variables:
 $ id_patient: int  2 3 4 5 6 7 8 9 10 11 ...
 $ id_stay   : int  2 3 4 356121 6 7 8 9 10 11 ...
 $ case_date : num  517 2024 241 123 381 ...
 - attr(*, "sorted")= chr "id_patient"
 - attr(*, ".internal.selfref")=<externalptr>
 - attr(*, "vars")=List of 1
  ..$ : symbol id_patient
```

**Comment by jomuller** [comment]
Errors comes from `dplyr`. Tested with `dplyr` 0.4.3 with success

**Comment by jomuller** [comment]
@gficheur We did the same test on the same moment  :-)

**Comment by gficheur** [comment]
@jomuller :-)

The structure associated with the object "obj1" looks very different with the 2 versions of dplyr.

Using dplyr v0.5.0, the structure associated with the field "$ case_date" (str(obj1)) has changed and has still 350,000 elements which seems to be part of the problem

**Comment by jomuller** [comment]
Yes, furthermore, there is some warnings that don't exists with dplyr 0.4.3 when simulated data is processed 

```
> x <- simulate_ep_data()
Warning messages:
1: In bind_rows_(x, .id) :
  binding factor and character vector, coercing into character vector
2: In bind_rows_(x, .id) :
  binding factor and character vector, coercing into character vector
```

**Comment by gficheur** [comment]
Interesting. We discussed this point with @acarongithub few hours ago, it works exactly as if the complete list of levels of a factor were required.

Is it possible to set the specific field as a character vector? Your warning messages are close to this problem.

**Comment by jomuller** [comment]
I tried to refactor the `simulate_ep_data` function but problem is not here. The error is clearly logical, due to a behavior change of one dplyr's function. @acarongithub could you try to deal with this, a least find some narrower clue ? I have to dig very deep in the code to try to understand but I'm not sure I will have the time to find it tomorrow.

**Comment by jomuller** [comment]
According to [`dplyr` 0.5.0 release notes](https://github.com/hadley/dplyr/releases/tag/v0.5.0), we should focus on breaking changes, then checking the following functions: 

- `arrange()` -> ignores grouping. Should be the key, because `arrange()` is used after grouping in *exclusion.R* in [line 16](https://github.com/jomuller/ITCARES/blob/7c4c1f41a83f28c1bd6c59dd391b9c876ae90b10/R/exclusions.R#L15-L16) and [line 24](https://github.com/jomuller/ITCARES/blob/7c4c1f41a83f28c1bd6c59dd391b9c876ae90b10/R/exclusions.R#L24-L25)
- `distinct()` -> only keeps the distinct variables

Also check if there is no use of deprecated function like `chain()`, `chain_q()`, `%.%`, `id()`, `rbind_all()` and `rbind_list()`.

**Comment by acarongithub** [comment]
I'm starting the tests

**Comment by jomuller** [comment]
A [possible quickfix is described here](https://github.com/hadley/dplyr/issues/1206#issuecomment-228493708):

> FWIW, you can get the old behavior by prefixing the columns in the arrange() call with the ones in the group_by() call, e.g.
>
> `mtcars %>% group_by(cyl) %>% arrange(mpg)`
> 
> vs
> 
> `mtcars %>% group_by(cyl) %>% arrange(cyl, mpg)`
